version: "2"
services:
  critical:
    build: .
    environment:
      - URL
      - DIMENSION=${DIMENSION:-1300x900}
      - LOCATION=${LOCATION:-output/critical.css}
    volumes:
      - ./output:/var/app/output/
