version: "2"
services:
  critical:
    build: .
    environment:
      - URL
      - DIMENSIONS
      - LOCATION: ${LOCATION:-/var/app/output/critical.css}
    volumes:
      - ./output:/var/app/output/
